// Code generated by "stringer -type=KeyCommand"; DO NOT EDIT.

package input

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Forward-0]
	_ = x[Backward-1]
	_ = x[Right-2]
	_ = x[Left-3]
	_ = x[Headlights-4]
	_ = x[Turbo-5]
}

const _KeyCommand_name = "ForwardBackwardRightLeftLigthsTurbo"

var _KeyCommand_index = [...]uint8{0, 7, 15, 20, 24, 30, 35}

func (i KeyCommand) String() string {
	if i < 0 || i >= KeyCommand(len(_KeyCommand_index)-1) {
		return "KeyCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyCommand_name[_KeyCommand_index[i]:_KeyCommand_index[i+1]]
}
