// Code generated by "stringer -type=ValueCommand"; DO NOT EDIT.

package input

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Release-0]
	_ = x[Press-1]
	_ = x[Hold-2]
}

const _ValueCommand_name = "ReleasePressHold"

var _ValueCommand_index = [...]uint8{0, 7, 12, 16}

func (i ValueCommand) String() string {
	if i < 0 || i >= ValueCommand(len(_ValueCommand_index)-1) {
		return "ValueCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueCommand_name[_ValueCommand_index[i]:_ValueCommand_index[i+1]]
}
